<<<<<<< HEAD
# Generated by Django 5.0.4 on 2024-05-06 12:41
=======
# Generated by Django 5.0.4 on 2024-05-06 13:26
>>>>>>> main

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name='Estate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('living_space', models.FloatField()),
                ('number_rooms', models.IntegerField()),
                ('has_balcony', models.BooleanField()),
                ('house_type', models.TextField(choices=[('VILLA', 'Villa'), ('SINGLE_HOUSE', 'Single House'), ('FARM_HOUSE', 'Farm House'), ('BIFAMILIAR_HOUSE', 'Bifamiliar House'), ('ROW_HOUSE', 'Row House'), ('MULTIPLE_DWELLING', 'Multiple Dwelling'), ('CHALET', 'Chalet'), ('TERRACE_HOUSE', 'Terrace House')])),
=======
            name='estate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('living_space', models.FloatField()),
                ('number_rooms', models.IntegerField()),
                ('has_balcony', models.BooleanField()),
                ('house_type', models.TextField(choices=[('1', 'VILLA'), ('2', 'SINGLE_HOUSE'), ('3', 'FARM_HOUSE'), ('4', 'BIFAMILIAR_HOUSE'), ('5', 'ROW_HOUSE'), ('6', 'MULTIPLE_DWELLING'), ('7', 'CHALET'), ('8', 'TERRACE_HOUSE')])),
>>>>>>> main
                ('year_built', models.IntegerField()),
            ],
        ),
    ]
