# Generated by Django 5.0.4 on 2024-05-06 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('living_space', models.FloatField()),
                ('number_rooms', models.IntegerField()),
                ('has_balcony', models.BooleanField()),
                ('house_type', models.TextField(choices=[('VILLA', 'Villa'), ('SINGLE_HOUSE', 'Single House'), ('FARM_HOUSE', 'Farm House'), ('BIFAMILIAR_HOUSE', 'Bifamiliar House'), ('ROW_HOUSE', 'Row House'), ('MULTIPLE_DWELLING', 'Multiple Dwelling'), ('CHALET', 'Chalet'), ('TERRACE_HOUSE', 'Terrace House')])),
                ('year_built', models.IntegerField()),
            ],
        ),
    ]
